{{- if .Values.kyvernoPolicyExceptions.enabled }}
  {{- if .Capabilities.APIVersions.Has "kyverno.io/v2alpha1/PolicyException" -}}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: {{ include "trivy-operator-helpers.name" . }}-exception
  namespace: {{ .Values.kyvernoPolicyExceptions.namespace | default .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
spec:
  exceptions:
    - policyName: disallow-host-namespaces
      ruleNames:
        - host-namespaces
        - autogen-host-namespaces
        - autogen-cronjob-host-namespaces
  match:
    any:
      - resources:
          kinds:
            - Job
            - Pod
          namespaces:
            - {{ .Release.Namespace }}
          names:
            - "node-collector-*"
  {{- end -}}
{{- end -}}
