{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "trivy-operator.networkPolicy" . }}-networkpolicy
  labels: {{- include "trivy-operator-helpers.labels" . | nindent 4 }}
  annotations:
    ignore-check.kube-linter.io/dangling-networkpolicy: "The podselector value, app.kubernetes.io/managed-by:trivy-operator is inherited from parent repository."
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  egress:
    # Allow egress to Kubernetes API server.
    - ports:
      - port: 443
        protocol: TCP
      to:
      - ipBlock:
          cidr: 172.16.0.0/12
      - ipBlock:
          cidr: 192.168.0.0/16
      - ipBlock:
          cidr: 10.0.0.0/8
    # Allow DNS.
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "trivy-operator.networkPolicy" . }}-scanner-job-networkpolicy
  labels: {{- include "trivy-operator-helpers.labels" . | nindent 4 }}
  annotations:
    ignore-check.kube-linter.io/dangling-networkpolicy: "The podselector value, app.kubernetes.io/managed-by:trivy-operator is inherited from parent repository."
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      {{- include "scannerjob.labels.selector" . | nindent 6 }}
  egress:
    # Allow egress to the internet to fetch database updates.
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
    # Allow DNS.
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector: {}
---
{{- end }}
