{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "trivy-operator.networkPolicy" . }}-networkpolicy
  labels: {{- include "trivy-operator-helpers.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  egress:
    # Allow egress for health checks.
    - ports:
      - port: 443
        protocol: TCP
    # Allow DNS.
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "trivy-operator.networkPolicy" . }}-scanner-job-networkpolicy
  labels: {{- include "trivy-operator-helpers.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      {{- include "scannerjob.labels.selector" . | nindent 6 }}
  egress:
    # Allow egress to the internet to fetch database updates.
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          # except:
          #   - 10.0.0.0/8
          #   - 172.16.0.0/12
          #   - 192.168.0.0/16
    # Allow DNS.
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector: {}
---
{{- end }}
