{{- if .Values.specs.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "trivy-operator.specInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "trivy-operator.specInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "trivy-operator.specInstall" . | quote }}
    {{- include "trivy-operator.selectorLabels" . | nindent 4 }}
    role: {{ include "trivy-operator.specInstallSelector" . | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - aquasecurity.github.io
  resources:
  - clustercompliancereports
  verbs:
  - create
  - delete
  - get
  - patch
  {{- if not .Values.global.podSecurityStandards.enforced }}
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "trivy-operator.specInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "trivy-operator.specInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "trivy-operator.specInstall" . | quote }}
    {{- include "trivy-operator.labels" . | nindent 4 }}
    role: {{ include "trivy-operator.specInstallSelector" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "trivy-operator.specInstall" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "trivy-operator.specInstall" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
