{{- if .Values.specs.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trivy-operator.specInstall" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "trivy-operator.specInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "trivy-operator.specInstall" . | quote }}
    {{- include "trivy-operator.selectorLabels" . | nindent 4 }}
    role: {{ include "trivy-operator.specInstallSelector" . | quote }}
{{- end }}
