{{ if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "trivy-operator.specInstall" . }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-7"
    {{- include "trivy-operator.specInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "trivy-operator.specInstall" . | quote }}
    {{- include "trivy-operator.selectorLabels" . | nindent 4 }}
    role: {{ include "trivy-operator.specInstallSelector" . | quote }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: {{ include "trivy-operator.specInstall" . | quote }}
      {{- include "trivy-operator.selectorLabels" . | nindent 6 }}
  egress:
    # To scrape the vault token expiration
    - toEntities:
        - kube-apiserver
{{ end }}
