apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/trivy-operator
  contents:
  - path: charts/trivy-operator
    git:
      url: https://github.com/giantswarm/trivy-operator-upstream
      ref: v0.6.0
    includePaths:
      - deploy/helm/**/*
    excludePaths:
      - deploy/helm/crds
    newRootPath: deploy/helm
  - path: crds
    git:
      url: https://github.com/giantswarm/trivy-operator-upstream
      ref: v0.6.0
    includePaths:
      - deploy/crd/*
    newRootPath: deploy/crd

