{{/*
We have to create individual configmaps for each CRD - they exceed the total
allowed length for a configmap if they are combined.
*/}}
{{ $currentScope := . }}
{{- if .Values.crds.install }}
  {{- range $path, $_ := .Files.Glob "crds/**" }}
    {{- with $currentScope }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trivy-operator.crdInstall" . }}-{{ $path | base | trimSuffix ".yaml" | replace "_" "-" | replace "." "-" }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
    {{- include "trivy-operator.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "trivy-operator.crdInstall" . | quote }}
    {{- include "trivy-operator.selectorLabels" . | nindent 4 }}
    role: {{ include "trivy-operator.CRDInstallSelector" . | quote }}
data:
  content: |
{{ .Files.Get $path | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
