version: 2.1
orbs:
  # used by renovate
  # repo: giantswarm/architect-orb
  architect: giantswarm/architect@5.1.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
      # Build chart and push to catalogs.
      - architect/push-to-app-catalog:
          context: "architect"
          name: push-trivy-operator-to-control-plane-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "trivy-operator"
          executor: "app-build-suite"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "push-trivy-operator-to-giantswarm-catalog"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "trivy-operator"
          persist_chart_archive: true
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      # Run app-test-suite tests.
      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to main.
            branches:
              ignore:
                - main
          requires:
            - push-trivy-operator-to-giantswarm-catalog

      # Push trivy-operator to app collections
      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-operator-to-aws-app-collection
          app_name: "trivy-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-trivy-operator-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-operator-to-azure-app-collection
          app_name: "trivy-operator"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-trivy-operator-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-operator-to-capa-app-collection
          app_name: "trivy-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-trivy-operator-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-operator-to-capz-app-collection
          app_name: "trivy-operator"
          app_collection_repo: "capz-app-collection"
          requires:
            - push-trivy-operator-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-operator-to-cloud-director-app-collection
          app_name: "trivy-operator"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-trivy-operator-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-operator-to-gcp-app-collection
          app_name: "trivy-operator"
          app_collection_repo: "gcp-app-collection"
          requires:
            - push-trivy-operator-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-operator-to-vsphere-app-collection
          app_name: "trivy-operator"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-trivy-operator-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
