version: 2.1
orbs:
  architect: giantswarm/architect@4.21.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      # Build chart and push to catalogs.
      - architect/push-to-app-catalog:
          context: "architect"
          name: push-trivy-operator-to-control-plane-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "trivy-operator"
          executor: "app-build-suite"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "push-trivy-operator-to-giantswarm-catalog"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "trivy-operator"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-trivy-operator-to-giantswarm-catalog
