name: Sync from fork

on:
  push:
    branches:
      - 'main' # Run at every sync
      - 'test-automation' # For testing
  schedule:
    - cron: '0 7 */7 * *' # At 07:00 on every 7th day-of-month

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-app-trivy-operator-with-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          # Get the last tag from fork repo
          LAST_TAG=$(git ls-remote --tags --sort='v:refname' --refs https://github.com/giantswarm/trivy-operator-upstream \
           | tail -1 | cut -d '/' -f3)
          # Modify the version in Vendir config
          git checkout -b ''main#update-chart''
          sed -i -r "s/(ref:).*/\1 $LAST_TAG/g" vendir.yml
          git add vendir.yml
          git commit -m "Update app version from fork repo"
          git push origin 'main#update-chart'
